### ISSUE TITLE
适配4.2

### ISSUE THREAD

**Issue by Arlene947** [F-19-F/amLyric#1]
![Screenshot_2023-04-10-22-51-42-343_info.muge.appshare.jpg](https://user-images.githubusercontent.com/128675053/230925985-b5c4634b-5fd3-4a60-b784-32ea2c8bf31d.jpg)

 生产队的驴都不敢这么歇 速速更新别逼我跪下了求你

**Comment by lovedxc** [comment]
目前的版本可以正常使用在4.2版本，不知你是否可以？

**Comment by Arlene947** [comment]
> 目前的版本可以正常使用在4.2版本，不知你是否可以？

目前4.1都不行 别说4.2啦

**Comment by lovedxc** [comment]
![Uploading Screenshot_2023-07-15-22-52-43-97_b842316e563230167e12cc31f5ffaf19.jpg…]()
4.2版本没有问题的

**Comment by Arlene947** [comment]
> ![Uploading Screenshot_2023-07-15-22-52-43-97_b842316e563230167e12cc31f5ffaf19.jpg…]()
> 4.2版本没有问题的
> 

墨桌 重构版的还是老版？

**Comment by Arlene947** [comment]
> ![Uploading Screenshot_2023-07-15-22-52-43-97_b842316e563230167e12cc31f5ffaf19.jpg…]()
> 4.2版本没有问题的
> 

我这 am4.1+重构+f19/getter 都不行
